// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "time_statement$string$1", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time_statement", "symbols": ["time_statement$string$1", "_", "time_predicate"], "postprocess": d=>d[2]},
    {"name": "time_statement$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time_statement", "symbols": ["time_statement$string$2", "_", "time_period"], "postprocess": d=>d[2]},
    {"name": "time_statement", "symbols": ["time_predicate"], "postprocess": id},
    {"name": "time_statement$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time_statement$ebnf$1$subexpression$1", "symbols": ["time_statement$ebnf$1$subexpression$1$string$1"]},
    {"name": "time_statement$ebnf$1$subexpression$1$string$2", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time_statement$ebnf$1$subexpression$1", "symbols": ["time_statement$ebnf$1$subexpression$1$string$2"]},
    {"name": "time_statement$ebnf$1", "symbols": ["time_statement$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "time_statement$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time_statement$ebnf$2", "symbols": ["_"], "postprocess": id},
    {"name": "time_statement$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time_statement", "symbols": ["filter", "_", "time_statement$ebnf$1", "time_statement$ebnf$2", "time_predicate"], "postprocess": d=>({
            type:"filter-predicate",
            filter: d[0],
            time_predicate:d[4]
        })},
    {"name": "filter$string$1", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "filter", "symbols": ["filter$string$1"], "postprocess": d=>(_index)=>true},
    {"name": "filter$string$2", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "filter", "symbols": ["filter$string$2"], "postprocess": d=>(_index)=>index % 2 === 0},
    {"name": "filter$string$3", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "filter", "symbols": ["filter$string$3", "_", "ordinal"], "postprocess": d=>(_index)=>index % d[2].value === 0},
    {"name": "time_predicate$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time_predicate$ebnf$1$subexpression$1", "symbols": ["_", "time_predicate$ebnf$1$subexpression$1$string$1", "_", "time_predicate"]},
    {"name": "time_predicate$ebnf$1", "symbols": ["time_predicate$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "time_predicate$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time_predicate", "symbols": ["stime_predicate", "time_predicate$ebnf$1"]},
    {"name": "stime_predicate$ebnf$1$subexpression$1$ebnf$1$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "stime_predicate$ebnf$1$subexpression$1$ebnf$1", "symbols": ["stime_predicate$ebnf$1$subexpression$1$ebnf$1$string$1"], "postprocess": id},
    {"name": "stime_predicate$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "stime_predicate$ebnf$1$subexpression$1$ebnf$2", "symbols": ["_"], "postprocess": id},
    {"name": "stime_predicate$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "stime_predicate$ebnf$1$subexpression$1", "symbols": ["_", "stime_predicate$ebnf$1$subexpression$1$ebnf$1", "stime_predicate$ebnf$1$subexpression$1$ebnf$2", "time"]},
    {"name": "stime_predicate$ebnf$1", "symbols": ["stime_predicate$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "stime_predicate$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "stime_predicate", "symbols": ["double_exact_date", "stime_predicate$ebnf$1"]},
    {"name": "time_period$subexpression$1", "symbols": [{"literal":"a"}]},
    {"name": "time_period$subexpression$1", "symbols": ["digit"]},
    {"name": "time_period$ebnf$1", "symbols": [{"literal":"s"}], "postprocess": id},
    {"name": "time_period$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time_period", "symbols": ["time_period$subexpression$1", "_", "epoch", "time_period$ebnf$1"]},
    {"name": "epoch$string$1", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$1"]},
    {"name": "epoch$string$2", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$2"]},
    {"name": "epoch$string$3", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$3"]},
    {"name": "epoch$string$4", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$4"]},
    {"name": "epoch$string$5", "symbols": [{"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$5"]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"6"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"7"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"8"}]},
    {"name": "digit$subexpression$1", "symbols": [{"literal":"9"}]},
    {"name": "digit", "symbols": ["digit$subexpression$1"], "postprocess": id},
    {"name": "digits$ebnf$1", "symbols": ["digit"]},
    {"name": "digits$ebnf$1", "symbols": ["digits$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "digits", "symbols": ["digits$ebnf$1"], "postprocess": d=>ParseInt(d.join(""))},
    {"name": "ordinal$subexpression$1$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ordinal$subexpression$1", "symbols": ["ordinal$subexpression$1$string$1"]},
    {"name": "ordinal$subexpression$1$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ordinal$subexpression$1", "symbols": ["ordinal$subexpression$1$string$2"]},
    {"name": "ordinal$subexpression$1$string$3", "symbols": [{"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ordinal$subexpression$1", "symbols": ["ordinal$subexpression$1$string$3"]},
    {"name": "ordinal", "symbols": ["digits", "ordinal$subexpression$1"], "postprocess": d=>({
            type:"ordinal",
            value:d,
        })},
    {"name": "double_exact_date$ebnf$1$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "double_exact_date$ebnf$1$subexpression$1$subexpression$1", "symbols": ["double_exact_date$ebnf$1$subexpression$1$subexpression$1$string$1"]},
    {"name": "double_exact_date$ebnf$1$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "double_exact_date$ebnf$1$subexpression$1$subexpression$1", "symbols": ["double_exact_date$ebnf$1$subexpression$1$subexpression$1$string$2"]},
    {"name": "double_exact_date$ebnf$1$subexpression$1", "symbols": ["_", "double_exact_date$ebnf$1$subexpression$1$subexpression$1", "_", "exact_date"]},
    {"name": "double_exact_date$ebnf$1", "symbols": ["double_exact_date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "double_exact_date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "double_exact_date", "symbols": ["exact_date", "double_exact_date$ebnf$1"], "postprocess": d=>{
            const g1 = d[0]
            const g2 = d[5]
            if(!g2) return g1
            return (start)=> function*(){
                const gen1 = g1(start);
                const gen2 = g2(start);
                let iter = 0
                while(gen1.next() && gen2.next()){
                    iter++
                    if(iter > 10){
                        return null;
                    }
                    if(gen1.value.getTime() === gen2.value.getTime()){
                        yield gen1.value;
                    }
                }
            }
        }},
    {"name": "exact_date", "symbols": ["slash_date"]},
    {"name": "exact_date", "symbols": ["dash_date"]},
    {"name": "exact_date", "symbols": ["date"]},
    {"name": "exact_date", "symbols": ["day"]},
    {"name": "exact_date", "symbols": ["month"]},
    {"name": "slash_date", "symbols": ["digits", {"literal":"/"}, "digits", {"literal":"/"}, "digits"]},
    {"name": "dash_date", "symbols": ["digits", {"literal":"-"}, "digits", {"literal":"-"}, "digits"]},
    {"name": "month$string$1", "symbols": [{"literal":"j"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$1"]},
    {"name": "month$string$2", "symbols": [{"literal":"f"}, {"literal":"e"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$2"]},
    {"name": "month$string$3", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$3"]},
    {"name": "month$string$4", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$4"]},
    {"name": "month$string$5", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$5"]},
    {"name": "month$string$6", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$6"]},
    {"name": "month$string$7", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$7"]},
    {"name": "month$string$8", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$8"]},
    {"name": "month$string$9", "symbols": [{"literal":"o"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$9"]},
    {"name": "month$string$10", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$10"]},
    {"name": "month$string$11", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$11"]},
    {"name": "month$string$12", "symbols": [{"literal":"j"}, {"literal":"a"}, {"literal":"n"}, {"literal":"u"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$12"]},
    {"name": "month$string$13", "symbols": [{"literal":"f"}, {"literal":"e"}, {"literal":"b"}, {"literal":"u"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$13"]},
    {"name": "month$string$14", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"r"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$14"]},
    {"name": "month$string$15", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$15"]},
    {"name": "month$string$16", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$16"]},
    {"name": "month$string$17", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$17"]},
    {"name": "month$string$18", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$18"]},
    {"name": "month$string$19", "symbols": [{"literal":"A"}, {"literal":"u"}, {"literal":"g"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$19"]},
    {"name": "month$string$20", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"p"}, {"literal":"t"}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$20"]},
    {"name": "month$string$21", "symbols": [{"literal":"o"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$21"]},
    {"name": "month$string$22", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$22"]},
    {"name": "month$string$23", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "month", "symbols": ["month$string$23"]},
    {"name": "day$string$1", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$1"]},
    {"name": "day$string$2", "symbols": [{"literal":"t"}, {"literal":"u"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$2"]},
    {"name": "day$string$3", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$3"]},
    {"name": "day$string$4", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$4"]},
    {"name": "day$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$5"]},
    {"name": "day$string$6", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$6"]},
    {"name": "day$string$7", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$7"]},
    {"name": "day$string$8", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$8"]},
    {"name": "day$string$9", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$9"]},
    {"name": "day$string$10", "symbols": [{"literal":"t"}, {"literal":"u"}, {"literal":"e"}, {"literal":"s"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$10"]},
    {"name": "day$string$11", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$11"]},
    {"name": "day$string$12", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$12"]},
    {"name": "day$string$13", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$13"]},
    {"name": "day$string$14", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$14"]},
    {"name": "day$string$15", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "day", "symbols": ["day$string$15"]},
    {"name": "date$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2", "symbols": ["digits"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date", "_", "digits", "date$ebnf$1", "date$ebnf$2"]},
    {"name": "date$ebnf$3$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$string$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$4", "symbols": ["_"], "postprocess": id},
    {"name": "date$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$5$subexpression$1$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "date$ebnf$5$subexpression$1", "symbols": ["date$ebnf$5$subexpression$1$string$1"]},
    {"name": "date$ebnf$5$subexpression$1$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "date$ebnf$5$subexpression$1", "symbols": ["date$ebnf$5$subexpression$1$string$2"]},
    {"name": "date$ebnf$5$subexpression$1$string$3", "symbols": [{"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "date$ebnf$5$subexpression$1", "symbols": ["date$ebnf$5$subexpression$1$string$3"]},
    {"name": "date$ebnf$5", "symbols": ["date$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$6$subexpression$1$string$1", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "date$ebnf$6$subexpression$1", "symbols": ["date$ebnf$6$subexpression$1$string$1"]},
    {"name": "date$ebnf$6", "symbols": ["date$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$7", "symbols": ["_"], "postprocess": id},
    {"name": "date$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$8", "symbols": ["digits"], "postprocess": id},
    {"name": "date$ebnf$8", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$3", "date$ebnf$4", "digits", "date$ebnf$5", "_", "date$ebnf$6", "_", "month", "date$ebnf$7", "date$ebnf$8"]},
    {"name": "_", "symbols": [{"literal":" "}]},
    {"name": "noon$string$1", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noon", "symbols": ["noon$string$1"]},
    {"name": "noon$string$2", "symbols": [{"literal":"p"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noon", "symbols": ["noon$string$2"]},
    {"name": "time$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time", "symbols": ["digits", "time$ebnf$1", "noon"]},
    {"name": "time$ebnf$2", "symbols": ["noon"], "postprocess": id},
    {"name": "time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "time", "symbols": ["digits", {"literal":":"}, "digits", "_", "time$ebnf$2"]},
    {"name": "time$string$1", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time", "symbols": ["time$string$1"]},
    {"name": "time$string$2", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time", "symbols": ["time$string$2"]},
    {"name": "time$string$3", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time", "symbols": ["time$string$3"]},
    {"name": "time$string$4", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time", "symbols": ["time$string$4"]},
    {"name": "time$string$5", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time", "symbols": ["time$string$5"]}
]
  , ParserStart: "time_statement"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
